
/*
 * Auto generated Run-Time-Environment Component Configuration File
 *      *** Do not modify ! ***
 *
 * Project: 'AirSense' 
 * Target:  'AirSense' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

#define RTE_DEVICE_STDPERIPH_ADC
#define RTE_DEVICE_STDPERIPH_BKP
#define RTE_DEVICE_STDPERIPH_DBGMCU
#define RTE_DEVICE_STDPERIPH_DMA
#define RTE_DEVICE_STDPERIPH_EXTI
#define RTE_DEVICE_STDPERIPH_FLASH
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
#define RTE_DEVICE_STDPERIPH_GPIO
#define RTE_DEVICE_STDPERIPH_I2C
#define RTE_DEVICE_STDPERIPH_IWDG
#define RTE_DEVICE_STDPERIPH_PWR
#define RTE_DEVICE_STDPERIPH_RCC
#define RTE_DEVICE_STDPERIPH_RTC
#define RTE_DEVICE_STDPERIPH_SPI
#define RTE_DEVICE_STDPERIPH_TIM
#define RTE_DEVICE_STDPERIPH_USART

#endif /* RTE_COMPONENTS_H */
